/**
 * GENERATED CODE - DO NOT MODIFY
 */
import { type ValidationResult, BlobRef } from '@atproto/lexicon'
import { CID } from 'multiformats/cid'
import { validate as _validate } from '../../../../lexicons'
import {
  type $Typed,
  is$typed as _is$typed,
  type OmitKey,
} from '../../../../util'

const is$typed = _is$typed,
  validate = _validate
const id = 'social.soapstone.text.en'

/** Base phrase for the message where the '****' is replaced with a fillPhrase value */
export type BasePhrases =
  | '**** ahead'
  | 'Be wary of ****'
  | 'Try ****'
  | 'Need ****'
  | 'Imminent ****...'
  | 'Weakness:****'
  | '****'
  | '****?'
  | 'Good Luck'
  | 'I did it!'
  | 'Here!'
  | "I can't take this..."
  | 'Praise the Sun!'
/** Character types that can be used in the fill phrase */
export type Characters =
  | 'Enemy'
  | 'Tough enemy'
  | 'Hollow'
  | 'Soldier'
  | 'Knight'
  | 'Sniper'
  | 'Caster'
  | 'Giant'
  | 'Skeleton'
  | 'Ghost'
  | 'Bug'
  | 'Poison bug'
  | 'Lizard'
  | 'Drake'
  | 'Flier'
  | 'Golem'
  | 'Statue'
  | 'Monster'
  | 'Strange creature'
  | 'Demon'
  | 'Darkwraith'
  | 'Dragon'
  | 'Boss'
/** Objects that can be used in the fill phrase */
export type Objects =
  | 'Bonfire'
  | 'Fog wall'
  | 'Humanity'
  | 'Lever'
  | 'Switch'
  | 'Key'
  | 'Treasure'
  | 'Chest'
  | 'Weapon'
  | 'Shield'
  | 'Projectile'
  | 'Armour'
  | 'Item'
  | 'Ring'
  | 'Sorcery scroll'
  | 'Pyromancy scroll'
  | 'Miracle scroll'
  | 'Ember'
  | 'Trap'
  | 'Covenant'
  | 'Amazing key'
  | 'Amazing treasure'
  | 'Amazing chest'
  | 'Amazing weapon'
  | 'Amazing shield'
  | 'Amazing projectile'
  | 'Amazing armour'
  | 'Amazing item'
  | 'Amazing ring'
  | 'Amazing sorcery scroll'
  | 'Amazing pyromancy scroll'
  | 'Amazing miracle scroll'
  | 'Amazing ember'
  | 'Amazing trap'
/** Techniques that can be used in the fill phrase */
export type Techniques =
  | 'Close-ranged battle'
  | 'Ranged battle'
  | 'Eliminating one at a time'
  | 'Luring it out'
  | 'Beating to a pulp'
  | 'Lying in ambush'
  | 'Stealth'
  | 'Mimicry'
  | 'Pincer attack'
  | 'Hitting them in one swoop'
  | 'Fleeing'
  | 'Charging'
  | 'Stabbing in the back'
  | 'Sweeping attack'
  | 'Shield breaking'
  | 'Head shots'
  | 'Sorcery'
  | 'Pyromancy'
  | 'Miracles'
  | 'Jumping off'
  | 'Sliding down'
  | 'Dashing through'
/** Action types that can be used in the fill phrase */
export type Actions =
  | 'Rolling'
  | 'Backstepping'
  | 'Jumping'
  | 'Attacking'
  | 'Holding with both hands'
  | 'Kicking'
  | 'A plunging attack'
  | 'Blocking'
  | 'Parrying'
  | 'Locking-on'
/** Geography types that can be used in the fill phrase */
export type Geography =
  | 'Path'
  | 'Hidden path'
  | 'Shortcut'
  | 'Detour'
  | 'Illusionary wall'
  | 'Shortcut'
  | 'Dead end'
  | 'Swamp'
  | 'Lava'
  | 'Forest'
  | 'Cave'
  | 'Labyrinth'
  | 'Safe zone'
  | 'Danger zone'
  | 'Sniper spot'
  | 'Bright spot'
  | 'Dark spot'
  | 'Open area'
  | 'Tight spot'
  | 'Hidden place'
  | 'Exchange'
  | 'Gorgeous view'
  | 'Fall'
/** Orientation types that can be used in the fill phrase */
export type Orientation =
  | 'Front'
  | 'Back'
  | 'Left'
  | 'Right'
  | 'Up'
  | 'Down'
  | 'Feet'
  | 'Head'
  | 'Back'
/** Body parts that can be used in the fill phrase */
export type BodyParts =
  | 'Head'
  | 'Neck'
  | 'Stomach'
  | 'Back'
  | 'Arm'
  | 'Leg'
  | 'Heel'
  | 'Rear'
  | 'Tail'
  | 'Wings'
  | 'Anywhere'
/** Attributes that can be used in the fill phrase */
export type Attributes =
  | 'Strike'
  | 'Thrust'
  | 'Slash'
  | 'Magic'
  | 'Fire'
  | 'Lightning'
  | 'Critical hits'
  | 'Bleeding'
  | 'Poison'
  | 'Strong poison'
  | 'Curses'
  | 'Divine'
  | 'Occult'
  | 'Crystal'
